// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWQfkUCAqBoRHGiN7AaL0ZgvqXkOVaRk',
    appId: '1:938027868749:web:f3b01615147dc3f904f204',
    messagingSenderId: '938027868749',
    projectId: 'momogram-8e072',
    authDomain: 'momogram-8e072.firebaseapp.com',
    storageBucket: 'momogram-8e072.appspot.com',
    measurementId: 'G-JW6F18HFSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfwdsIfiP5wq8laPFMF00R3NpTqyznHTc',
    appId: '1:938027868749:android:48ef2bf0e100111f04f204',
    messagingSenderId: '938027868749',
    projectId: 'momogram-8e072',
    storageBucket: 'momogram-8e072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjxbbjOe9z7wppbrXIG95yAka41q0RrEs',
    appId: '1:938027868749:ios:f96be170f7c8230a04f204',
    messagingSenderId: '938027868749',
    projectId: 'momogram-8e072',
    storageBucket: 'momogram-8e072.appspot.com',
    iosBundleId: 'com.example.momogram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjxbbjOe9z7wppbrXIG95yAka41q0RrEs',
    appId: '1:938027868749:ios:89e7f2876ef6cc3904f204',
    messagingSenderId: '938027868749',
    projectId: 'momogram-8e072',
    storageBucket: 'momogram-8e072.appspot.com',
    iosBundleId: 'com.example.momogram.RunnerTests',
  );
}
